persentation_WorkoutR/Controllers/exerciseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using dataAccessLayer;
using persentation_WorkoutR.Models;
using utilityLogger;


namespace persentation_WorkoutR.Controllers
{
    public class exerciseController : Controller
    {
        // making new instance of presentation mapper
        static presentationMapper _mapper = new presentationMapper();
        // making new instance of exercise data eccess
        static exerciseDataAccess _exerciseDataAccess = new exerciseDataAccess();
        // making new instance of the logger
        static logger _logger = new logger();

        // GET: exercise
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult addExercise(exerciseModel _addExercise)
        {
            if ((int)Session["FK_roleID"] == 2 || (int)Session["FK_roleID"] == 3)
            {
                try
                {
                    // if model state is valid
                    if (ModelState.IsValid)
                    {

                        try
                        {
                            // adding exercise to the database
                            _exerciseDataAccess.addingExercise(_mapper.map(_addExercise));
                            // return back to exercises view
                            return RedirectToAction("viewExercise");
                        }
                        catch (Exception _error)
                        {
                            // putting error into a file
                            _logger.logError(_error);
                        }
                    }
                    return View();
                }
                catch (Exception _error)
                {
                    // putting error into a file
                    _logger.logError(_error);
                }
            }

            return View("Error");
        }

        [HttpPost]
        public ActionResult updateExercise(exerciseModel _updateExercise)
        {
            if ((int)Session["FK_roleID"] == 2 || (int)Session["FK_roleID"] == 3)
            {
                try
                {
                    // if model state is valid
                    if (ModelState.IsValid)
                    {
                        try
                        {
                            // updating the exercise in the database
                            _exerciseDataAccess.updateExercise(_mapper.map(_updateExercise));
                            // return back to exercise view
                            return RedirectToAction("viewExercise");
                        }
                        catch (Exception _error)
                        {
                            // putting error into a file
                            _logger.logError(_error);
                        }
                    }
                    return View();
                }
                catch (Exception _error)
                {
                    // putting error into a file
                    _logger.logError(_error);
                }
            }
            return View("Error");
        }

        //HTTP GET______________________________________________________________________________

        [HttpGet]
        public ActionResult addExercise()
        {
            if ((int)Session["FK_roleID"] == 2 || (int)Session["FK_roleID"] == 3)
            {
                // return add exercise view
                return View("addExercise");
            }

            return View("Error");
        }

        [HttpGet]
        // setting action name to update exercise
        [ActionName("updateExercise")]
        public ActionResult updateExerciseGet(exerciseModel _updateExercise)
        {
            if ((int)Session["FK_roleID"] == 2 || (int)Session["FK_roleID"] == 3)
            {
                try
                {
                    // making session variable using exercise model 
                    Session["exerciseID"] = _updateExercise.exerciseID;
                    // return back update exercise view 
                    return View(_updateExercise);
                }
                catch (Exception _error)
                {
                    // putting error into a file
                    _logger.logError(_error);
                }
            }

            return View("Error");
        }

        [HttpGet]
        public ActionResult deleteExercise(int _deleteExercise)
        {
            if ((int)Session["FK_roleID"] == 2 || (int)Session["FK_roleID"] == 3)
            {
                try
                {
                    // delete exercise from the database with the exercise id
                    _exerciseDataAccess.deletingExercise(_deleteExercise);
                    // return back to exercise view
                    return RedirectToAction("viewExercise");
                }
                catch (Exception _error)
                {
                    // putting error into a file
                    _logger.logError(_error);
                }
            }
            return View("Error");
        }

        [HttpGet]
        public ActionResult viewExercise()
        {
            if ((int)Session["FK_roleID"] == 2 || (int)Session["FK_roleID"] == 3)
            {
                try
                {

                    // making new instance of the view model 
                    viewModel viewExercise = new viewModel();
                    // listing all exercises into exercise list from the database
                    viewExercise.exerciseList = _mapper.map(_exerciseDataAccess.listAllExercise());
                    // returning back the viewExercise page with the list
                    return View(viewExercise);
                }
                catch (Exception _error)
                {
                    // putting error into a file
                    _logger.logError(_error);
                }
            }
            // return the the error page
            return View("Error");
        }

    }
}

persentation_WorkoutR/Controllers/routineController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using dataAccessLayer;
using dataAccessLayer.Objects;
using persentation_WorkoutR.Models;
using utilityLogger;
using businessLogicLayer;
using businessLogicLayer.Objects;

namespace persentation_WorkoutR.Controllers
{
    public class routineController : Controller
    {

        // making new instances of the presentation mapper 
        static presentationMapper _mapper = new presentationMapper();
        // making new instance of the business logic mapper
        static BL_mapper _blMapper = new BL_mapper();
        // new instance of routine data access
        static routineDataAccess _routineDataAccess = new routineDataAccess();
        // new instance of workout logic from business logic
        workoutLogic _workoutLogic = new workoutLogic();
        // new instance of the logger
        static logger _logger = new logger();

        // GET: routine
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult addRoutine(routineModel _addRoutine)
        {
            if ((int)Session["FK_roleID"] == 1 || (int)Session["FK_roleID"] == 2 || (int)Session["FK_roleID"] == 3 && _addRoutine.FK_personID == (int)Session["personID"])
            {
                try
                {
                    // if model state is valid
                    if (ModelState.IsValid)
                    {
                        try
                        {
                            // adding routine back to the database 
                            _routineDataAccess.addingRoutine(_mapper.map(_addRoutine));

                            // redirecting back to view Routine   
                            return RedirectToAction("viewRoutine");
                        }
                        catch (Exception _error)
                        {
                            // putting error into a file
                            _logger.logError(_error);
                        }
                    }
                    return View();
                }
                catch (Exception _error)
                {
                    // putting error into a file
                    _logger.logError(_error);
                }
            }
            // returning error page
            return View("Error");
        }

        [HttpPost]
        public ActionResult updateRoutine(routineModel _updateRoutine)
        {
            if ((int)Session["FK_roleID"] == 1 || (int)Session["FK_roleID"] == 2 || (int)Session["FK_roleID"] == 3)
            {
                try
                {
                    // if model state is valid
                    if (ModelState.IsValid)
                    {
                        try
                        {
                            // updating the routine in database
                            _routineDataAccess.updateRoutine(_mapper.map(_updateRoutine));
                            // redirecting back to view routine
                            return RedirectToAction("viewRoutine");
                        }
                        catch (Exception _error)
                        {
                            // putting error into a file
                            _logger.logError(_error);
                        }
                    }
                    return View();
                }
                catch (Exception _error)
                {
                    // putting error into a file
                    _logger.logError(_error);
                }
            }
            // return error page
            return View("Error");
        }

        //HTTP GET______________________________________________________________________________

        [HttpGet]
        // making the action name to add routine
        [ActionName("addRoutine")]
        public ActionResult addRoutineGet(routineModel _addRoutine)
        {
            if ((int)Session["FK_roleID"] == 1 || (int)Session["FK_roleID"] == 2 || (int)Session["FK_roleID"] == 3)
            {
                // adding personID variable from session to the routine 
                _addRoutine.FK_personID = (int)Session["personID"];
                // getting the add routine view
                return View(_addRoutine);
            }
            return View("Error");
        }

        [HttpGet]
        public ActionResult viewRoutine()
        {
            if ((int)Session["FK_roleID"] == 1 || (int)Session["FK_roleID"] == 2 || (int)Session["FK_roleID"] == 3)
            {
                try
                {
                    // making int variable personid to view routines for that member
                    int _personID = (int)Session["personID"];

                    // new instance of view model 
                    viewModel viewRoutine = new viewModel();
                    // getting the list from view model to map it the data access to view all routines
                    viewRoutine.routineList = _mapper.map(_routineDataAccess.listAllRoutine(_personID));


                    //making a for loop to count total sets and reps for the routine
                    for (int i = 0; i < viewRoutine.routineList.Count(); i++)
                    {
                        // making an int variable to hold routineid
                        int _routineID = viewRoutine.routineList[i].routineID;
                        // make data access object with listing single routine
                        routineDAO routine = _routineDataAccess.listSingleRoutine(_personID, _routineID);
                        // calling in the business logic layer with the object and routine and person id's
                        _workoutLogic.addSets(_blMapper.map(routine), _routineID, _personID);
                    }
                    return View(viewRoutine);
                }
                catch (Exception _error)
                {
                    // putting error into a file
                    _logger.logError(_error);
                }
            }
            return View("Error");
        }

        [HttpGet]
        [ActionName("updateRoutine")]
        public ActionResult updateRoutineGet(routineModel routine)
        {
            if ((int)Session["FK_roleID"] == 1 || (int)Session["FK_roleID"] == 2 || (int)Session["FK_roleID"] == 3)
            {
                try
                {
                    //  making session id routine and person id with routine model
                    Session["routineID"] = routine.routineID;
                    Session["FK_personID"] = routine.FK_personID;

                    // returning view of routine 
                    return View(routine);
                }
                catch (Exception _error)
                {
                    // putting error into a file
                    _logger.logError(_error);
                }
            }
            // return to error page
            return View("Error");
        }

        [HttpGet]
        public ActionResult deleteRoutine(int _deleteRoutine)
        {
            if ((int)Session["FK_roleID"] == 1 || (int)Session["FK_roleID"] == 2 || (int)Session["FK_roleID"] == 3)
            {
                try
                {
                    // deleting routine based on the routine id in the database
                    _routineDataAccess.deletingRoutine(_deleteRoutine);
                    // redirecting back to view routines
                    return RedirectToAction("viewRoutine");
                }
                catch (Exception _error)
                {
                    // putting error into a file
                    _logger.logError(_error);
                }
            }
            // return to error page
            return View("Error");
        }

    }
}

persentation_WorkoutR/Views/person/View1.cshtml
@model persentation_WorkoutR.Models.personModel
    @using persentation_WorkoutR.Models
@{
    ViewBag.Title = "profile";
}
<h2> User Profile </h2>
<div class="container">
    <div class="row profile">
        <div class="col-md-3">
            <div class="profile-sidebar">
                <!-- SIDEBAR USERPIC -->
                <div class="profile-userpic">
                    <img src="http://keenthemes.com/preview/metronic/theme/assets/admin/pages/media/profile/profile_user.jpg" class="img-responsive" alt="">
                </div>
                <!-- END SIDEBAR USERPIC -->
                <!-- SIDEBAR USER TITLE -->
                <div class="profile-usertitle">
                    <div class="profile-usertitle-name">

                    </div>
                    <div class="profile-usertitle-job">


                    </div>
                </div>
                <!-- END SIDEBAR USER TITLE -->
                <!-- SIDEBAR BUTTONS -->

                <!-- END SIDEBAR BUTTONS -->
                <!-- SIDEBAR MENU -->
                <div class="profile-usermenu">
                    <ul class="nav">
                        <li class="active">
                            <a href="#">
                                @Html.DisplayFor(m => m.personFirstName)
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                @if ((int)Session["FK_roleID"] ==1 || (int)Session["FK_roleID"] == 2|| (int)Session["FK_roleID"] == 3)
                                {
                                    @Html.ActionLink("Profile", "updatePerson", "person", Model, null);                                  
                                }
                            </a>
                        </li>
                        <li>
                            <a href="#" target="_blank">
                                @if ((int)Session["FK_roleID"] == 1 || (int)Session["FK_roleID"] == 2 || (int)Session["FK_roleID"] == 3)
                                {
                                    @Html.ActionLink("My routines", "viewRoutine", "routine")

                                }
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                @if ((int)Session["FK_roleID"] == 2 || (int)Session["FK_roleID"] == 3)
                                {
                                    @Html.ActionLink("Members", "viewPerson", "person")
                                }
                            </a>
                        </li>
                        <li>
                            <a href="#">              
                                @if ((int)Session["FK_roleID"] == 2 || (int)Session["FK_roleID"] == 3)
                                {
                                    @Html.ActionLink("Exercise", "viewExercise", "exercise")

                                }
                            </a>
                        </li>
                    </ul>
                </div>
                <!-- END MENU -->
            </div>
        </div>
        <div class="col-md-9">
            <div class="profile-content">
                Some user related content goes here...
            </div>
        </div>
    </div>
</div>

persentation_WorkoutR/Views/person/login.cshtml
@model persentation_WorkoutR.Models.personModel

@{ 
    /**/

    ViewBag.Title = "login";
}
    <div class="w3ls-login box box--big">
        @using (Html.BeginForm("login", "person", FormMethod.Post))
        {
            <div class="container">
                <div class="agile-field-txt">

                    @Html.LabelFor(m => m.personUsername)
                    @Html.TextBoxFor(m => m.personUsername, new { @class = "form-control", @placeholder = "Enter your name" })
                    @Html.ValidationMessageFor(m => m.personUsername)
                </div>
                <div class="agile-field-txt">
                    @Html.LabelFor(m => m.personPassword)
                    @Html.PasswordFor(m => m.personPassword, new { @class = "form-control", @placeholder = "Password", @id = "myInput" })
                    @Html.ValidationMessageFor(m => m.personPassword)
                    <br />
                    <input id="check3" name="check3" type="checkbox" value="show password" onclick="myFunction()">

                    <label class="check" for="check3">Show password</label>
                </div>
                <!-- script for show password -->
                <script>
                    function myFunction() {
                        var x = document.getElementById("myInput");
                        if (x.type === "password") {
                            x.type = "text";
                        } else {
                            x.type = "password";
                        }
                    }
                </script>
                <!-- //script ends here -->

                <div class="w3ls-bot">
                    <div class="form-end">
                        <input onclick="change()" class="btn-danger" type="submit" value="LOGIN" id="myButton1">
                    </div>
                    <div class="clearfix"></div>
                </div>

                <!-- script for logging in... function -->
                <script type="text/javascript">
                    function change() {
                        document.getElementById("myButton1").value = "Logging in...";
                    }
                </script>
                <!-- //script ends here -->
            </div>
        }
    </div>

persentation_WorkoutR/Views/person/profile.cshtml
@model persentation_WorkoutR.Models.personModel
@using persentation_WorkoutR.Models
@{
    ViewBag.Title = "View";
}

<style>
    #header {
        background-color: black;
        color: white;
        width: 100%;
        text-align: center;
        padding: 5px;
    }

    .left {
        width: 100px;
        float: left;
        text-align: left;
    }

    .right {
        width: 100px;
        float: left;
        text-align: right;
    }

    hr {
        margin: 10px 0;
        border: 1px thin;
    }

    #nav {
        line-height: 30px;
        background-color: #eeeeee;
        height: 350px;
        width: 25%;
        float: left;
        padding: 5px;
    }

    #section {
        width: 350px;
        float: left;
        width: 75%;
        padding-left: 120px;
        padding-top: 25px;
    }
</style>
<div id="header">
    <h1>Welcome, @Html.DisplayFor(m => m.personFirstName)</h1>
</div>

<div id="nav">
    <div class="left">First Name:</div> <div class="right">@Html.DisplayFor(m => m.personFirstName)</div><br />
    <hr />
    <div class="left">Last Name:</div> <div class="right">@Html.DisplayFor(m => m.personLastName)</div><br />
    <hr />
    <div class="left">Phone #:</div> <div class="right">@Html.DisplayFor(m => m.personPhone)</div><br />
    <hr />
    <div class="left">Address:</div> <div class="right">@Html.DisplayFor(m => m.personAddress)</div><br />
    <hr />
    <div class="left">City:</div> <div class="right">@Html.DisplayFor(m => m.personCity)</div><br />
    <hr />
    <div class="left">State:</div> <div class="right">@Html.DisplayFor(m => m.personState)</div><br />
    <hr />
    <div class="left">Zipcode:</div> <div class="right">@Html.DisplayFor(m => m.personZip)</div><br />
    <hr />

    @if ((int)Session["FK_roleID"] == 1 || (int)Session["FK_roleID"] == 2 || (int)Session["FK_roleID"] == 3)
    {
        @Html.ActionLink("Edit Profile", "updatePerson", "person", Model, null) <i style="padding:10px"></i>
        <br />
        @Html.ActionLink("Update User/Password", "updatePassPerson", "person", Model, null)
        <br />
    }
</div>
<div id="section">
    <p>
        @if ((int)Session["FK_roleID"] == 1 || (int)Session["FK_roleID"] == 2 || (int)Session["FK_roleID"] == 3)
        {
            <a href='@Url.Action("viewRoutine", "routine")'>
                <img src="~/images/BeFunky-photo.jpg" width="600" , height="250" />
            </a>
        }
    </p><br />
   <p>
        @if ((int)Session["FK_roleID"] == 2 || (int)Session["FK_roleID"] == 3)
        {
            <a href='@Url.Action("viewPerson", "person")'>
                <img src="~/images/Legend_Fitness_HappyMembers.jpg" width="600" , height="250" />
            </a>
        }
    </p><br />
    <p>
        @if ((int)Session["FK_roleID"] == 2 || (int)Session["FK_roleID"] == 3)
        {
            <a href='@Url.Action("viewExercise", "exercise")'>
                <img src="~/images/dumbbells_gym_weight_disks_118338_1920x1080.jpg" width="600" , height="250" />
            </a>
        }
    </p><br />
</div>
<br />
<br />

persentation_WorkoutR/Views/person/register.cshtml
@model persentation_WorkoutR.Models.personModel
@{
    /**/

    ViewBag.Title = "register";
}

<div class="w3ls-register box box--big">
    @using (Html.BeginForm("register", "person", FormMethod.Post))
    {

        @Html.ValidationSummary()
        <div class="container">
            <h2>REGISTER</h2><br />
            <div class="form-group">

                @Html.LabelFor(m => m.personFirstName)
                @Html.TextBoxFor(m => m.personFirstName, new { @class = "form-control", @placeholder = "Enter your First Name", @required = true })
                @Html.ValidationMessageFor(m => m.personFirstName)
            </div>

            <div class="form-group">
                @Html.LabelFor(m => m.personLastName)
                @Html.TextBoxFor(m => m.personLastName, new { @class = "form-control", @placeholder = "Enter your Last Name", @required = true })
                @Html.ValidationMessageFor(m => m.personLastName)
            </div>

            <div class="form-group">
                @Html.LabelFor(m => m.personAddress)
                @Html.TextBoxFor(m => m.personAddress, new { @class = "form-control", @placeholder = "Address", @required = true })
                @Html.ValidationMessageFor(m => m.personAddress)
            </div>

            <div class="form-group">
                @Html.LabelFor(m => m.personCity)
                @Html.TextBoxFor(m => m.personCity, new { @class = "form-control", @placeholder = "City", @required = true })
                @Html.ValidationMessageFor(m => m.personCity)
            </div>

            <div class="form-group">
                @Html.LabelFor(m => m.personState)
                @Html.TextBoxFor(m => m.personState, new { @class = "form-control", @placeholder = "State", @required = true })
                @Html.ValidationMessageFor(m => m.personState)
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.personZip)
                @Html.TextBoxFor(m => m.personZip, new { @class = "form-control", @placeholder = "Zip code", @required = true })
                @Html.ValidationMessageFor(m => m.personZip)
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.personPhone)
                @Html.TextBoxFor(m => m.personPhone, new { @class = "form-control", @placeholder = "Phone number", @required = true })
                @Html.ValidationMessageFor(m => m.personPhone)
            </div>
            @* <div class="form-group">
                    @Html.HiddenFor(m => m.FK_roleID)
                    @Html.HiddenFor(m => m.FK_roleID, new { @class = "form-control" })
                </div>*@
            <div class="form-group">
                @Html.LabelFor(m => m.personUsername)
                @Html.TextBoxFor(m => m.personUsername, new { @class = "form-control", @placeholder = "User Name" })
                @Html.ValidationMessageFor(m => m.personUsername)
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.personPassword)
                @Html.PasswordFor(m => m.personPassword, new { @class = "form-control", @placeholder = "Password" })
                @Html.ValidationMessageFor(m => m.personPassword)
            </div>
        </div>
        <input type="submit" class="btn-danger" value="Register" />
    }
</div>

persentation_WorkoutR/Views/person/view2.cshtml
@model persentation_WorkoutR.Models.personModel
@using persentation_WorkoutR.Models
@{
    ViewBag.Title = "View";
}
<html>
<head>
    <title>HTML Layout using Tables</title>
</head>
<body>
    <table width="100%" border="0">

        <tr>
            <td colspan="4" bgcolor="#b5dcb3">
                <h1>Welcome, @Html.DisplayFor(m => m.personFirstName)</h1>
            </td>
        </tr>
        <tr valign="top">
            <td bgcolor="#aaa" width="50">
                <b>Profile</b><br />
                @Html.DisplayFor(m => m.personFirstName)<br />
                @Html.DisplayFor(m => m.personLastName)<br />
                @Html.DisplayFor(m => m.personAddress)<br />
                @Html.DisplayFor(m => m.personCity)<br />
                @Html.DisplayFor(m => m.personState)<br />
                @Html.DisplayFor(m => m.personPhone)<br />
                @Html.DisplayFor(m => m.personZip)<br />
            </td>
<tr>
            <td colspan="" bgcolor="#eee" width="100" height="200">
                @if ((int)Session["FK_roleID"] == 1 || (int)Session["FK_roleID"] == 2 || (int)Session["FK_roleID"] == 3)
                {                   
                    @Html.ActionLink("Profile", "updatePerson", "person", Model, null);
                }
            </td>

            <td bgcolor="#eee" width="100" height="200">

                @if ((int)Session["FK_roleID"] == 1 || (int)Session["FK_roleID"] == 2 || (int)Session["FK_roleID"] == 3)
                {
                    <a href='@Url.Action("viewRoutine", "routine")'>
                        <img src="~/images/1.jpg" width="400", height="250"/>
                    </a>                    
                }
                    <center>Routines</center>
            </td>
            
            <td bgcolor="#eee" width="100" height="200">
                @if ((int)Session["FK_roleID"] == 2 || (int)Session["FK_roleID"] == 3)
                {
                    <a href='@Url.Action("viewPerson", "person")'>
                        <img src="~/images/multiple-users-silhouette_318-49546.jpg" width="400" , height="250" />
                    </a>
                }
                <center>Members</center>
            </td>
        

            <td bgcolor="#eee" width="100" height="200">

                @if ((int)Session["FK_roleID"] == 2 || (int)Session["FK_roleID"] == 3)
                {
                    <a href='@Url.Action("viewExercise", "exercise")'>
                        <img src="~/images/WwMXoZ.jpg" width="400" , height="250" />
                    </a>
                }
                <center>Exercises</center>
            </td>
        </tr>

    </table>
</body>
</html>