persentation_WorkoutR/Controllers/routineController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using dataAccessLayer;
using dataAccessLayer.Objects;
using persentation_WorkoutR.Models;
using utilityLogger;
using businessLogicLayer;
using businessLogicLayer.Objects;

namespace persentation_WorkoutR.Controllers
{
    public class routineController : Controller
    {

        // making new instances of the presentation mapper 
        static presentationMapper _mapper = new presentationMapper();
        // making new instance of the business logic mapper
        static BL_mapper _blMapper = new BL_mapper();
        // new instance of routine data access
        static routineDataAccess _routineDataAccess = new routineDataAccess();
        // new instance of workout logic from business logic
        workoutLogic _workoutLogic = new workoutLogic();
        // new instance of the logger
        static logger _logger = new logger();

        // GET: routine
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult addRoutine(routineModel _addRoutine)
        {
            if ((int)Session["FK_roleID"] == 1 || (int)Session["FK_roleID"] == 2 || (int)Session["FK_roleID"] == 3 && _addRoutine.FK_personID == (int)Session["personID"])
            {
                try
                {
                    // if model state is valid
                    if (ModelState.IsValid)
                    {
                        try
                        {
                            // adding routine back to the database 
                            _routineDataAccess.addingRoutine(_mapper.map(_addRoutine));

                            // redirecting back to view Routine   
                            return RedirectToAction("viewRoutine");
                        }
                        catch (Exception _error)
                        {
                            // putting error into a file
                            _logger.logError(_error);
                        }
                    }
                    return View();
                }
                catch (Exception _error)
                {
                    // putting error into a file
                    _logger.logError(_error);
                }
            }
            // returning error page
            return View("Error");
        }

        [HttpPost]
        public ActionResult updateRoutine(routineModel _updateRoutine)
        {
            if ((int)Session["FK_roleID"] == 1 || (int)Session["FK_roleID"] == 2 || (int)Session["FK_roleID"] == 3)
            {
                try
                {
                    // if model state is valid
                    if (ModelState.IsValid)
                    {
                        try
                        {
                            // updating the routine in database
                            _routineDataAccess.updateRoutine(_mapper.map(_updateRoutine));
                            // redirecting back to view routine
                            return RedirectToAction("viewRoutine");
                        }
                        catch (Exception _error)
                        {
                            // putting error into a file
                            _logger.logError(_error);
                        }
                    }
                    return View();
                }
                catch (Exception _error)
                {
                    // putting error into a file
                    _logger.logError(_error);
                }
            }
            // return error page
            return View("Error");
        }

        //HTTP GET______________________________________________________________________________

        [HttpGet]
        // making the action name to add routine
        [ActionName("addRoutine")]
        public ActionResult addRoutineGet(routineModel _addRoutine)
        {
            if ((int)Session["FK_roleID"] == 1 || (int)Session["FK_roleID"] == 2 || (int)Session["FK_roleID"] == 3)
            {
                // adding personID variable from session to the routine 
                _addRoutine.FK_personID = (int)Session["personID"];
                // getting the add routine view
                return View(_addRoutine);
            }
            return View("Error");
        }

        [HttpGet]
        public ActionResult viewRoutine()
        {
            if ((int)Session["FK_roleID"] == 1 || (int)Session["FK_roleID"] == 2 || (int)Session["FK_roleID"] == 3)
            {
                try
                {
                    // making int variable personid to view routines for that member
                    int _personID = (int)Session["personID"];

                    // new instance of view model 
                    viewModel viewRoutine = new viewModel();
                    // getting the list from view model to map it the data access to view all routines
                    viewRoutine.routineList = _mapper.map(_routineDataAccess.listAllRoutine(_personID));


                    //making a for loop to count total sets and reps for the routine
                    for (int i = 0; i < viewRoutine.routineList.Count(); i++)
                    {
                        // making an int variable to hold routineid
                        int _routineID = viewRoutine.routineList[i].routineID;
                        // make data access object with listing single routine
                        routineDAO routine = _routineDataAccess.listSingleRoutine(_personID, _routineID);
                        // calling in the business logic layer with the object and routine and person id's
                        _workoutLogic.addSets(_blMapper.map(routine), _routineID, _personID);
                    }
                    return View(viewRoutine);
                }
                catch (Exception _error)
                {
                    // putting error into a file
                    _logger.logError(_error);
                }
            }
            return View("Error");
        }

        [HttpGet]
        [ActionName("updateRoutine")]
        public ActionResult updateRoutineGet(routineModel routine)
        {
            if ((int)Session["FK_roleID"] == 1 || (int)Session["FK_roleID"] == 2 || (int)Session["FK_roleID"] == 3)
            {
                try
                {
                    //  making session id routine and person id with routine model
                    Session["routineID"] = routine.routineID;
                    Session["FK_personID"] = routine.FK_personID;

                    // returning view of routine 
                    return View(routine);
                }
                catch (Exception _error)
                {
                    // putting error into a file
                    _logger.logError(_error);
                }
            }
            // return to error page
            return View("Error");
        }

        [HttpGet]
        public ActionResult deleteRoutine(int _deleteRoutine)
        {
            if ((int)Session["FK_roleID"] == 1 || (int)Session["FK_roleID"] == 2 || (int)Session["FK_roleID"] == 3)
            {
                try
                {
                    // deleting routine based on the routine id in the database
                    _routineDataAccess.deletingRoutine(_deleteRoutine);
                    // redirecting back to view routines
                    return RedirectToAction("viewRoutine");
                }
                catch (Exception _error)
                {
                    // putting error into a file
                    _logger.logError(_error);
                }
            }
            // return to error page
            return View("Error");
        }

    }
}

persentation_WorkoutR/Controllers/routineWorkoutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using dataAccessLayer;
using persentation_WorkoutR.Models;
using utilityLogger;
using businessLogicLayer;
using businessLogicLayer.Objects;

namespace persentation_WorkoutR.Controllers
{
    public class routineWorkoutController : Controller
    {
        // making new instance of the presentation mapper
        static presentationMapper _mapper = new presentationMapper();
        // making new instance if routine Workout data access 
        static routineWorkoutDataAccess _routineWorkoutDataAccess = new routineWorkoutDataAccess();
        // making new instance of exercise data access
        static exerciseDataAccess _exerciseData = new exerciseDataAccess();
        // making new instance of logger
        static logger _logger = new logger();

        // GET: routine
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult addRoutineWorkout(routineWorkoutModel _addRoutineWorkout)
        {
            if ((int)Session["FK_roleID"] == 1 || (int)Session["FK_roleID"] == 2 || (int)Session["FK_roleID"] == 3)
            {
                try
                {
                    // if model state is valid
                    if (ModelState.IsValid)
                    {
                        try
                        {
                            // using session varible to get the FK routineWorkoutID 
                            _addRoutineWorkout.FK_routineWorkoutID = (int)Session["FK_routineWorkoutID"];
                            // then adding the the routin workout to the database with the ID
                            _routineWorkoutDataAccess.addingRoutineWorkout(_mapper.map(_addRoutineWorkout));

                            // making new instance of routine model
                            routineModel modelforID = new routineModel();
                            // setting routineID for modelforID to addingRoutineWorkout FK routineWorkout ID
                            modelforID.routineID = _addRoutineWorkout.FK_routineWorkoutID;

                            // return back to routineWorkout page that belongs to the modelforID
                            return RedirectToAction("viewRoutineWorkout", modelforID);
                        }
                        catch (Exception _error)
                        {
                            // putting error into a file
                            _logger.logError(_error);
                        }
                    }
                    return View();
                }
                catch (Exception _error)
                {
                    // putting error into a file
                    _logger.logError(_error);
                }
            }
            return View("Error");
        }

        [HttpPost]
        public ActionResult updateRoutineWorkout(routineWorkoutModel _updateRoutineWorkout)
        {
            if ((int)Session["FK_roleID"] == 1 || (int)Session["FK_roleID"] == 2 || (int)Session["FK_roleID"] == 3)
            {
                try
                {
                    // if model state is valid
                    if (ModelState.IsValid)
                    {
                        try
                        {
                            // getting the FK_routineWorkoutID from session variable FK_routineWorkoutID 
                            _updateRoutineWorkout.FK_routineWorkoutID = (int)Session["FK_routineWorkoutID"];

                            // updating the the routine exercises based to the id 
                            _routineWorkoutDataAccess.updateRoutineWorkout(_mapper.map(_updateRoutineWorkout));

                            // making new instance of routine model
                            routineModel modelforid = new routineModel();
                            // setting routineID to updated FK routineWorkoutID
                            modelforid.routineID = _updateRoutineWorkout.FK_routineWorkoutID;

                            // returning back the page view routine workout
                            return RedirectToAction("viewRoutineWorkout", modelforid);
                        }
                        catch (Exception _error)
                        {
                            // putting error into a file
                            _logger.logError(_error);
                        }
                    }
                    return View();
                }
                catch (Exception _error)
                {
                    // putting error into a file
                    _logger.logError(_error);
                }
            }
            return View("Error");
        }

        //HTTP GET______________________________________________________________________________

        [HttpGet]
        // setting action name to addRoutineWorkout
        [ActionName("addRoutineWorkout")]
        public ActionResult addRoutineWorkoutG()
        {
            if ((int)Session["FK_roleID"] == 1 || (int)Session["FK_roleID"] == 2 || (int)Session["FK_roleID"] == 3)
            {
                try
                {
                    // making new instance of the view model
                    viewModel viewExercise = new viewModel();
                    // using the database of all exercise and adding back to exercise list
                    viewExercise.exerciseList = _mapper.map(_exerciseData.listAllExercise());

                    // making new instance of routineWorkout model
                    routineWorkoutModel routineWorkoutModel = new routineWorkoutModel();
                    // populating the routineWorkoutmodel exercise list with view model exercise listt
                    routineWorkoutModel.exerciseList = viewExercise.exerciseList;
                    // setting variable view exercise to the routine workout model exercise list
                    Session["viewExercise"] = routineWorkoutModel.exerciseList;

                    // return the view  with routine workout model
                    return View(routineWorkoutModel);
                }
                catch (Exception _error)
                {
                    // putting error into a file
                    _logger.logError(_error);
                }
            }

            return View("Error");
        }

        [HttpGet]
        public ActionResult viewRoutineWorkout(routineModel _viewRoutine)
        {
            if ((int)Session["FK_roleID"] == 1 || (int)Session["FK_roleID"] == 2 || (int)Session["FK_roleID"] == 3)
            {

                try
                {
                    // setting personID to the session varibale personID
                    int _personID = (int)Session["personID"];

                    // showing routineID in url
                    // setting routineID to the view routine routineID
                    int _routineID = _viewRoutine.routineID;

                    // making new instance of the view model
                    viewModel viewRoutineW = new viewModel();
                    // populating routine workout list from the batabase that matches personID and routineID
                    viewRoutineW.routineWorkoutList = _mapper.map(_routineWorkoutDataAccess.listAllRoutineWorkout(_personID, _routineID));

                    // setting session variable FK_routineWorkoutID to view routine. routineID
                    Session["FK_routineWorkoutID"] = _viewRoutine.routineID;

                    // return back view with view routine Workout
                    return View(viewRoutineW);
                }
                catch (Exception _error)
                {
                    // putting error into a file
                    _logger.logError(_error);
                }
            }
            // return error page
            return View("Error");
        }


        [HttpGet]
        // setting action name 
        [ActionName("updateRoutineWorkout")]
        public ActionResult updateRoutineWorkoutGet(routineWorkoutModel routineWorkout)
        {
            if ((int)Session["FK_roleID"] == 1 || (int)Session["FK_roleID"] == 2 || (int)Session["FK_roleID"] == 3)
            {
                try
                {
                    // making new instance of view model
                    viewModel viewExercise = new viewModel();
                    // poplating exercise model, exercise list from database
                    viewExercise.exerciseList = _mapper.map(_exerciseData.listAllExercise());

                    routineWorkoutModel routineWorkoutModel = new routineWorkoutModel();
                    routineWorkoutModel.exerciseList = viewExercise.exerciseList;
                    Session["viewExercise"] = routineWorkoutModel.exerciseList;


                    // setting session varibale routineWorkoutID to routineWorkoutID
                    Session["routineWorkoutID"] = routineWorkout.routineWorkoutID;

                    // setting exercise list to view exercise model exercise list
                    routineWorkout.exerciseList = viewExercise.exerciseList;

                    // return view, routine Workout
                    return View(routineWorkout);
                }
                catch (Exception _error)
                {
                    // putting error into a file
                    _logger.logError(_error);
                }
            }
            // return back error page
            return View("Error");
        }

        [HttpGet]
        public ActionResult deleteRoutineWorkout(int _deleteRoutineWorkout)
        {
            if ((int)Session["FK_roleID"] == 1 || (int)Session["FK_roleID"] == 2 || (int)Session["FK_roleID"] == 3)
            {
                try
                {
                    // deleting the routineWorkout based to the ID from the database

persentation_WorkoutR/Views/routine/addRoutine.cshtml
@model persentation_WorkoutR.Models.routineModel

@{
    ViewBag.Title = "addRoutine";
}

<br />@Html.ActionLink("Back to List ", "viewRoutine", "routine")
<h2>ADD Routine</h2><br />

<div class="w3ls-routine box box--big">

    @using (Html.BeginForm("addRoutine", "routine", FormMethod.Post))
    {
        <div class="container">


            <div class="form-group">

                @Html.LabelFor(m => m.routineName)
                @Html.TextBoxFor(m => m.routineName, new { @class = "form-control", @placeholder = "Routine Name" })
                @Html.ValidationMessageFor(m => m.routineName, "", new { @class = "text-danger" })
            </div>

            <div class="form-group" style="display:none">
                @Html.LabelFor(m => m.FK_personID)
                @Html.TextBoxFor(m => m.FK_personID, new { @class = "form-control" })
            </div>

            <div class="form-group">
                @Html.LabelFor(m => m.login)
                @Html.EditorFor(m => m.login, new { @class = "form-control datepicker", @id = "datepicker" })
                @Html.ValidationMessageFor(m => m.login, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                @Html.HiddenFor(m => m.totalSets)
                @Html.HiddenFor(m => m.totalSets, new { @class = "form-control" })
            </div>
            <div class="form-group">
                @Html.HiddenFor(m => m.totalReps)
                @Html.HiddenFor(m => m.totalReps, new { @class = "form-control" })
            </div>
            <div class="form-group">
                @Html.HiddenFor(m => m.totalExercise)
                @Html.HiddenFor(m => m.totalExercise, new { @class = "form-control" })
            </div>
        </div>
        <input type="submit" class="btn-danger" value="Add Routine" />
    }
</div>

persentation_WorkoutR/Views/routine/updateRoutine.cshtml
@model persentation_WorkoutR.Models.routineModel
@{
    ViewBag.Title = "updateRoutine";
}

<br />@Html.ActionLink("Back to List ", "viewRoutine", "routine")
<h2>Update Routine</h2><br />
<div class="w3ls-routine box box--big">
    @using (Html.BeginForm("updateRoutine", "routine", FormMethod.Post))
    {
    <div class="container">


        <div class="form-group">

            @Html.HiddenFor(m => m.routineID)
            @Html.HiddenFor(m => m.routineID, new { @class = "form-control" })
        </div>

        <div class="form-group">

            @Html.LabelFor(m => m.routineName)
            @Html.EditorFor(m => m.routineName, new { @class = "form-control", @placeholder = "Routine Name" })
            @Html.ValidationMessageFor(m => m.routineName, "", new { @class = "text-danger" })
        </div>

        <div class="form-group" style="display:none;">

            @Html.HiddenFor(m => m.FK_personID)
            @Html.HiddenFor(m => m.FK_personID, new { @class = "form-control" })
        </div>

        <div class="form-group">

            @Html.LabelFor(m => m.login)
            @Html.EditorFor(m => m.login, new { @class = "form-control datepicker", @id = "datepicker" })
            @Html.ValidationMessageFor(m => m.login, "", new { @class = "text-danger" })
        </div>

        <div class="form-group" style="display:none;">

            @Html.HiddenFor(m => m.totalSets)
            @Html.HiddenFor(m => m.totalSets, new { @class = "form-control" })
        </div>
        <div class="form-group" style="display:none;">

            @Html.HiddenFor(m => m.totalReps)
            @Html.HiddenFor(m => m.totalReps, new { @class = "form-control" })
        </div>
        <div class="form-group" style="display:none;">

            @Html.HiddenFor(m => m.totalExercise)
            @Html.HiddenFor(m => m.totalExercise, new { @class = "form-control" })
        </div>

    </div>
        <input type="submit" class="btn-danger" value="Update" />
    }
</div>

persentation_WorkoutR/Views/routine/viewRoutine.cshtml
@model persentation_WorkoutR.Models.viewModel
@using persentation_WorkoutR.Models
@{

    ViewBag.Title = "viewRoutine";
}

<link href="https://use.fontawesome.com/releases/v5.0.7/css/all.css" rel="stylesheet">

<br> 
<h2>My Routines</h2>
@using (Html.BeginForm("viewRoutine", "routine", FormMethod.Post))
{
<head>
    <style>
        table {
            font-family: arial, sans-serif;
            border-collapse: collapse;
            width: 100%;
        }

        td, th {
            border: 1px solid #ffffff;
            text-align: left;
            padding: 8px;
            font-size: 15px;
        }

        tr:nth-child(even) {
            background-color: #ccc3c3;
        }
    </style>
</head>
    <table>
        <tr>
            <th>Routine Name</th>
            <th>Login Date</th>
            <th>Exercises</th>
            <th>Total Sets</th>
            <th>Total Reps</th>
        </tr>
        @foreach (routineModel routine in Model.routineList)
        {
            string parameterValue = routine.login.ToShortDateString();
        <tr>
            <td>@Html.DisplayFor(m => routine.routineName)</td>
            <td>@Html.DisplayFor(m => parameterValue)</td>
            <td>@Html.DisplayFor(m => routine.totalExercise)</td>
            <td>@Html.DisplayFor(m => routine.totalSets)</td>
            <td>@Html.DisplayFor(m => routine.totalReps)</td>
            <td>@Html.ActionLink("Exercises", "viewRoutineWorkout", "routineWorkout", routine, null) </td>
            <td>@Html.ActionLink("delete", "deleteRoutine", routeValues: new { _deleteRoutine = routine.routineID })<i class="fa fa-trash" style="font-size:14px; color:red; padding:5px"></i> </td>
            <td>@Html.ActionLink("update", "updateRoutine", routine)<i class="fa fa-edit" style="font-size:14px; color:red; padding:5px"></i></td>
        </tr>
        }
    </table>
    
}
<br />
<h3>Add Routine </h3>
<i class="fa fa-plus" style="font-size:17px; color:red; padding:5px"></i>@Html.ActionLink("Add Routine", "addRoutine", "routine")